### ISSUE TITLE
Null Pointer Exception Occurs When Searching for "dna repair"

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/cpath1#23]
_From @GoogleCodeExporter on March 16, 2015 20:14_

```
What steps will reproduce the problem?
1.  I searched for "dna repair"  

What is the expected output? What do you see instead?

I got a NullPointerException:

java.lang.NullPointerException
    at
org.apache.jsp.WEB_002dINF.jsp.pages.search.biopax_005fsearch_jsp._jspService(bi
opax_005fsearch_jsp.java:364)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:94)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:856)


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `cer...@gmail.com` on 2 Oct 2009 at 1:23

_Copied from original issue: PathwayCommons/cpath2#19_

**Comment by IgorRodchenkov** [comment]
_From @GoogleCodeExporter on March 16, 2015 20:14_

Original comment by `cer...@gmail.com` on 5 Oct 2009 at 6:10
- Changed state: **Fixed**

**Comment by IgorRodchenkov** [comment]
_From @GoogleCodeExporter on March 16, 2015 20:14_

Original comment by `cer...@gmail.com` on 5 Oct 2009 at 6:38
- Changed state: **TestDeployed**

**Comment by IgorRodchenkov** [comment]
_From @GoogleCodeExporter on March 16, 2015 20:14_

```
I didn't get any null pointer exception.
```

Original comment by `fkaz...@gmail.com` on 6 Oct 2009 at 5:05
- Changed state: **Verified**

**Comment by IgorRodchenkov** [comment]
_From @GoogleCodeExporter on March 16, 2015 20:14_

Original comment by `rod...@gmail.com` on 4 Jan 2013 at 11:59
- Added labels: **Product-cPath**
- Removed labels: **Project-cPath**
